# Generated by Django 2.0 on 2019-04-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cover_title',
            new_name='cover_url',
        ),
    ]
